# Install brew
# Run core
# Run install

- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - name: build ssh
      ansible.builtin.include_tasks: tasks/homebrew.yml
      tags:
        - homebrew
        - core
    - name: build git
      ansible.builtin.include_tasks: tasks/git.yml
      tags:
        - git
        - core
    - name: build core
      ansible.builtin.include_tasks: tasks/core.yml
      tags:
        - core
    - name: build zsh
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags:
        - zsh
        - core
    - name: build nvim
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags:
        - nvim
        - install
    - name: build dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - install
    - name: build productivity tools
      ansible.builtin.include_tasks: tasks/productivity-tools.yml
      tags:
        - productivity-tools
        - install
    - name: build lsp
      ansible.builtin.include_tasks: tasks/lsp.yml
      tags:
        - lsp
        - install
