- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
   - name: Include ssh
        ansible.builtin.include_tasks:
          file: task/ssh.yml    
   - name: Include git
        ansible.builtin.include_tasks:
          file: task/git.yml    
   - name: Include core
        ansible.builtin.include_tasks:
          file: task/core.yml    
   - name: Include zsh
        ansible.builtin.include_tasks:
          file: task/zsh.yml    
   - name: Include nvim
        ansible.builtin.include_tasks:
          file: task/nvim.yml    
   - name: Include dotfiles
        ansible.builtin.include_tasks:
          file: task/dotfiles.yml    
   - name: Include productivity tools
        ansible.builtin.include_tasks:
          file: task/productivity-tools.yml    
   - name: Include lsp
        ansible.builtin.include_tasks:
          file: task/lsp.yml    
