- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - name: build ssh
      ansible.builtin.include_task: tasks/ssh.yml
    - name: build git
      ansible.builtin.include_task: tasks/git.yml
    - name: build core
      ansible.builtin.include_task: tasks/core.yml
    - name: build zsh
      ansible.builtin.include_task: tasks/zsh.yml
    - name: build nvim
      ansible.builtin.include_task: tasks/nvim.yml
    - name: build dotfiles
      ansible.builtin.include_task: tasks/dotfiles.yml
    - name: build productivity tools
      ansible.builtin.include_task: tasks/productivity-tools.yml
    - name: build lsp
      ansible.builtin.include_task: tasks/lsp.yml
