- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_task: "tasks/ssh.yml"
    - include_task: "tasks/git.yml"
    - include_task: "tasks/core.yml"
    - include_task: "tasks/zsh.yml"
    - include_task: "tasks/nvim.yml"
    - include_task: "tasks/dotfiles.yml"
    - include_task: "tasks/productivity-tools.yml"
    - include_task: "tasks/lsp.yml"
