# Install brew
# Run core
# Run install

- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - name: build ssh
      ansible.builtin.include_tasks: tasks/ssh.yml
      tags:
        - homebrew
        - base
    - name: build git
      ansible.builtin.include_tasks: tasks/git.yml
      tags:
        - git
        - base
    - name: build core
      ansible.builtin.include_tasks: tasks/core.yml
      tags:
        - core
        - base
    - name: build zsh
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags:
        - base
        - zsh
    - name: build nvim
      ansible.builtin.include_tasks: tasks/nvim.yml
      tags:
        - install
        - nvim
    - name: build dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - install
    - name: build obsidian
      ansible.builtin.include_tasks: tasks/obsidian.yml
      tags:
        - install
        - obsidian
