- name: Installing stow
  community.general.homebrew:
    name: stow
  tags:
    - install
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:bear-jordan/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags:
    - install
    - dotfiles
