- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "bearjordan@gmail.com"
  tags:
  - git
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "bear-jordan"
  tags:
  - git
