- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - nvim
- name: Get Lazy
  ansible.builtin.git:
    repo: 'https://github.com/folke/lazy.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/lazy/lazy.nvim"
  tags:
    - install
    - nvim
- name: Clone Neovim
  community.general.homebrew:
    name: neovim
  tags:
    - install
    - nvim
