  - name: Setup zsh
    community.general.homebrew:
      name: zsh
    tags:
      - core
      - zsh
  - name: Change Shell
    become: true
    shell: chsh -s `which zsh` 
    tags:
      - core
      - zsh
  - name: Install zoxide
    community.general.homebrew:
      name: zoxide,fzf
    tags:
      - core
      - zsh
