  - name: Setup zsh
    become: true
    apt: name=zsh
    tags:
      - core
      - zsh
  - name: Change Shell
    become: true
    shell: chsh -s `which zsh` 
    tags:
      - core
      - zsh
  - name: Install zoxide
    become: true
    apt:
      name: ["zoxide", "fzf"]
    tags:
      - core
      - zsh
